# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mecha's - A Stellaris "Gestaltconsciousness" race
email: 4nn3ck@gmail.com
description: > # A Stellaris fanpage about a race of robots playing the game. 
        bla bla
baseurl: "/Mechas" # the subpath of your site, e.g. /blog
url: "http://4nn3ck73.github.io" # the base hostname & protocol for your site
twitter_username: mechas
github_username:  4nn3ck73

# Build settings
markdown: kramdown
